//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInsurance.BusinessLogic.Data
{
    using MyInsurance.BusinessLogic.Constants;
    using MyInsurance.BusinessLogic.Interfaces;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employee : ILoginable, IDataErrorInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Cases = new HashSet<Case>();
            this.Policies = new HashSet<Policy>();
            this.BirthDate = DateTime.Now;
        }

        public string this[string propertyName]
        {
            get
            {
                string errorMessage = String.Empty;
                switch (propertyName)
                {
                    case "FirstName":
                        if (string.IsNullOrEmpty(FirstName))
                            errorMessage = "Imiê musi byæ wpisane!";
                        else if (FirstName.Length < 3)
                            errorMessage = "Imiê musi mieæ minimum 3 znaki!";
                        else if (!Regexes.NAME_REGEX.IsMatch(FirstName))
                            errorMessage = "Imiê mo¿e zawieraæ wy³¹cznie litery i musi siê zaczynaæ z du¿ej!";
                        break;
                    case "LastName":
                        if (string.IsNullOrEmpty(LastName))
                            errorMessage = "Nazwisko musi byæ wpisane!";
                        else if (LastName.Length < 3)
                            errorMessage = "Nazwisko musi mieæ minimum 3 znaki!";
                        else if (!Regexes.NAME_REGEX.IsMatch(LastName))
                            errorMessage = "Nazwisko mo¿e zawieraæ wy³¹cznie litery i musi siê zaczynaæ z du¿ej!";
                        break;
                    case "Street":
                        if (string.IsNullOrEmpty(Street))
                            errorMessage = "Nazwa ulicy musi byæ wpisana!";
                        else if (Street.Length < 3)
                            errorMessage = "Nazwa ulicy musi mieæ minimum 3 znaki!";
                        else if (!Regexes.CITY_REGEX.IsMatch(Street))
                            errorMessage = "Nazwa ulicy mo¿e zawieraæ wy³¹cznie litery i musi siê zaczynaæ z du¿ej!";
                        break;
                    case "City":
                        if (string.IsNullOrEmpty(City))
                            errorMessage = "Nazwa miasta musi byæ wpisana!";
                        else if (City.Length < 3)
                            errorMessage = "Nazwa miasta mieæ minimum 3 znaki!";
                        else if (!Regexes.CITY_REGEX.IsMatch(City))
                            errorMessage = "Nazwa miasta mo¿e zawieraæ wy³¹cznie litery i musi siê zaczynaæ z du¿ej!";
                        break;
                    case "ZipCode":
                        if (!Regexes.ZIPCODE_REGEX.IsMatch(ZipCode))
                            errorMessage = "Wpisz prawid³owy kod pocztowy!";
                        break;
                    case "Pesel":
                        if (!Regexes.PESEL_REGEX.IsMatch(Pesel))
                            errorMessage = "Wpisz prawid³owy numer PESEL!";
                        break;
                    case "EmailAddress":
                        if (!Regexes.EMAIL_REGEX.IsMatch(EmailAddress))
                            errorMessage = "Wpisz prawid³owy adres e-mail!";
                        break;
                    case "PhoneNumber":
                        if (!Regexes.PHONENUMBER_REGEX.IsMatch(PhoneNumber))
                            errorMessage = "Wpisz prawid³owy numer telefonu!";
                        break;
                };
                return errorMessage;
            }
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public int HouseNumber { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Pesel { get; set; }
        public string EmailAddress { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsBoss { get; set; }
        public bool IsActive { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policies { get; set; }

        public string Error => throw new NotImplementedException();
    }
}
