//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInsurance.BusinessLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int CaseId { get; set; }
        public string Text { get; set; }
        public System.DateTime SendingDate { get; set; }
        public bool IsFromAgent { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
